#spring.application.name=registration
## ??H2???
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
## ???????
#spring.datasource.url=jdbc:h2:mem:articledb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
## ??SQL??????????
#spring.jpa.show-sql=true
spring:
    datasource:
        name: account_system  #数据库名
        url: jdbc:mysql://localhost:3306/account_system #url
        username: root  #用户名
        password: 20041013  #密码
        driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动

    jpa:
        hibernate:
            ddl-auto: update # 自动更新表结构
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect