spring:
    datasource:
        name: account_system  #数据库名
        url: jdbc:mysql://localhost:3306/account_system #url
        username: root  #用户名
        password: 123456  #密码
        driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动
        hikari:
            maximum-pool-size: 10
            connection-timeout: 30000

    jpa:
        hibernate:
            ddl-auto: update # 自动更新表结构
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect

